# Generated by Django 5.0.1 on 2024-01-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_remove_employee_email_remove_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.CharField(default=1112, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=1111, max_length=200),
            preserve_default=False,
        ),
    ]
